# Generated by Django 4.1.7 on 2023-03-09 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportdate',
            name='date',
            field=models.DateField(),
        ),
    ]
